<?php 
require_once('post-types.php');
require_once('elements.php');
require_once('sections.php');
require_once('modules.php');
require_once('shortcodes.php');
require_once('hooks.php');
require_once('theme-widgets.php');
require_once('svg.php');
require_once('menus.php');
require_once('ajax.php');
require_once('bootstrap-navwalker.php');